In [ ]:
from google.colab import files
uploaded = files.upload()

TypeError: 'NoneType' object is not subscriptable

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('diabetes.csv')

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.shape

(768, 9)

In [ ]:
df.isnull().sum()

pregnancies                   0
glucose                       5
bloodpressure                35
skinthickness               227
insulin                     374
bmi                          11
diabetespedigreefunction      0
age                           0
outcome                       0
dtype: int64

In [ ]:
(df == 0).any()

pregnancies                  True
glucose                     False
bloodpressure               False
skinthickness               False
insulin                     False
bmi                         False
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
df.columns=df.columns.str.strip().str.lower()

In [ ]:
# columns where 0 is not a valid medical vallue

invalid_zero_cols = [
    'glucose',
    'bloodpressure',
    'skinthickness',
    'insulin',
    'bmi'
]

# replace 0 with nan
df[invalid_zero_cols] = df[invalid_zero_cols].replace(0, np.nan)

In [ ]:
# impute missing values

for col in invalid_zero_cols:
    df[col].fillna(df[col].median(),inplace=True)# impute missing values

NameError: name 'invalid_zero_cols' is not defined

In [ ]:
# feature target separation

x = df.drop('outcome',axis=1)

# target
y = df['outcome']

In [ ]:
x.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age'],
      dtype='object')

In [ ]:
y.name

'outcome'

In [ ]:
# train and test split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(
   x,y,test_size=0.2,random_state=42,stratify=y
  )

In [ ]:
x_train.shape,x_test.shape

((614, 8), (154, 8))

In [ ]:
y.value_counts(normalize=True)

outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64

In [ ]:
y_train.value_counts(normalize=True)

outcome
0    0.651466
1    0.348534
Name: proportion, dtype: float64

In [ ]:
y_test.value_counts(normalize=True)


outcome
0    0.649351
1    0.350649
Name: proportion, dtype: float64

In [ ]:
# feature scaling

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
# here using logistic regression classifier because it is a
# binary classification problem, strong baseline for  medical data

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train_scaled,y_train)

# here now the model train, uses scaled features, can implement safely

LogisticRegression()

In [ ]:
# predictions

y_pred = log_reg.predict(x_test_scaled)


In [ ]:
y_pred[:10]

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
log_reg.score(x_test_scaled,y_test)

# accuracy of test

0.7077922077922078

In [ ]:
# accuracy of train
log_reg.score(x_train_scaled,y_train)

0.7964169381107492

In [ ]:
# linear regression probability prediction
y_prob = log_reg.predict_proba(x_test_scaled)

In [ ]:
y_prob[:20]

array([[0.39028927, 0.60971073],
       [0.88164424, 0.11835576],
       [0.70653687, 0.29346313],
       [0.7491633 , 0.2508367 ],
       [0.96679333, 0.03320667],
       [0.83147615, 0.16852385],
       [0.5118357 , 0.4881643 ],
       [0.07632489, 0.92367511],
       [0.91856595, 0.08143405],
       [0.1614104 , 0.8385896 ],
       [0.71899374, 0.28100626],
       [0.52026804, 0.47973196],
       [0.87078686, 0.12921314],
       [0.89824015, 0.10175985],
       [0.71148172, 0.28851828],
       [0.64772427, 0.35227573],
       [0.27674359, 0.72325641],
       [0.91551102, 0.08448898],
       [0.18674072, 0.81325928],
       [0.89115055, 0.10884945]])

In [ ]:
y_prob_diabetic = y_prob[:,1]
y_prob_diabetic[:10]

array([0.60971073, 0.11835576, 0.29346313, 0.2508367 , 0.03320667,
       0.16852385, 0.4881643 , 0.92367511, 0.08143405, 0.8385896 ])

In [ ]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm
# [TN,FP]
# [FN,TP]

# TN - true negative - actually non diabetic
# TP - true positive - actually non diabetic but predicted  diabetic
# FN - false negative - actually diabetic but predicted non diabetic
# PP - false positive - actually diabetic

array([[82, 18],
       [27, 27]])

In [ ]:
# classification report

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

# here we will see about precision, recall, f1 score and support
# precision: how correct the model was when it said it said 0 or 1
# recall: how many real 0 and 1 it found
# files:balance score of precision and recall
# support : how many actual 0 and 1 patients

# example for weighted avg
# classes with more samples influence the final score more than the smaller classes

              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.60      0.50      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154



In [ ]:
# next model we using here is SVM Support Vector Machine, it finds a strong,
# margin based decision boundary that ofeten improved recall on small,
# well scalled datasets

# the main reason to use is small in size,
# we did the scaling, change are high to get better recall

In [ ]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear',probability=True)
svm_model.fit(x_train_scaled,y_train)

SVC(kernel='linear', probability=True)

In [ ]:
y_pred_svm = svm_model.predict(x_test_scaled)

# evaluation
svm_model.score(x_test_scaled,y_test)

0.7012987012987013

In [ ]:
y_pred_svm = svm_model.predict(x_test_scaled)

In [ ]:
y_pred_svm[:10]

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
# confusion metrix

from sklearn.metrics import confusion_matrix, classification_report
cm_svm = confusion_matrix(y_test,y_pred_svm)
cm

array([[82, 18],
       [27, 27]])

In [ ]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.59      0.48      0.53        54

    accuracy                           0.70       154
   macro avg       0.67      0.65      0.66       154
weighted avg       0.69      0.70      0.69       154



In [ ]:
# RDC AUC Receiver operating characteristic, Area Under the Curve

from sklearn.metrics import roc_auc_score
roc_auc_lr = roc_auc_score(y_test,y_prob[:,1])
roc_auc_svm = roc_auc_score(y_test,y_pred_svm)

roc_auc_lr,roc_auc_svm


# 81 for both lr and svm
# roc implies that both LR and SVM correctly ranks a diabetics higher
# that a non diabetic 82% of the time
# slides the threshould from 0 - 1, computes recall and false positive
# at each step, plots the curve


(np.float64(0.812962962962963), np.float64(0.6507407407407407))